In [1]:
import numpy as np

In [3]:
# Add
a = np.array([10, 10, 10])
b = np.array([5, 5, 5])
a + b

array([15, 15, 15])

In [7]:
a - b

array([5, 5, 5])

In [6]:
a * b

array([50, 50, 50])

In [8]:
a / b

array([2., 2., 2.])

In [9]:
a % b

array([0, 0, 0])

In [10]:
a % 3

array([1, 1, 1])

In [11]:
a < 35

array([ True,  True,  True])

In [16]:
# Element-wise multiplication
a1 = np.array([[1,2], 
               [3,4]])

a2 = np.array([[5,6], 
               [7,8]])
a1 * a2

array([[ 5, 12],
       [21, 32]])

In [17]:
# Matrix multiplication
a1.dot(a2)

array([[19, 22],
       [43, 50]])

In [19]:
np.dot(a1, a2)

array([[19, 22],
       [43, 50]])

In [20]:
np.dot(a2, a1)

array([[23, 34],
       [31, 46]])

In [24]:
a1 *= 3
a1

array([[ 27,  54],
       [ 81, 108]])

In [30]:
a2

array([[5, 6],
       [7, 8]])

In [31]:
a2.sum()

26

In [32]:
a2.mean()

6.5

In [33]:
a2.sum(axis=0)

array([12, 14])

In [34]:
a2.sum(axis=1)

array([11, 15])