In [1]:
import numpy as np

In [2]:
a = np.arange(9)

In [7]:
a1, a2, a3 = np.split(a,3)
a1

array([0, 1, 2])

In [8]:
a2

array([3, 4, 5])

In [9]:
a3

array([6, 7, 8])

In [5]:
np.split(a, [2,7])

[array([0, 1]), array([2, 3, 4, 5, 6]), array([7, 8])]

In [13]:
a = np.array([['Germany', 'Austria', 'France', 'Hungary'], ['Berlin', 'Vienna', 'Paris', 'Budapest']])

In [11]:
np.hsplit(a,2)

[array([['Germany', 'Austria'],
        ['Berlin', 'Vienna']], dtype='<U8'), array([['France', 'Hungary'],
        ['Paris', 'Budapest']], dtype='<U8')]

In [12]:
np.hsplit(a.T,2)

[array([['Germany'],
        ['Austria'],
        ['France'],
        ['Hungary']], dtype='<U8'), array([['Berlin'],
        ['Vienna'],
        ['Paris'],
        ['Budapest']], dtype='<U8')]

In [14]:
np.split(a, 2)

[array([['Germany', 'Austria', 'France', 'Hungary']], dtype='<U8'),
 array([['Berlin', 'Vienna', 'Paris', 'Budapest']], dtype='<U8')]

In [15]:
# Same as split
np.vsplit(a,2)

[array([['Germany', 'Austria', 'France', 'Hungary']], dtype='<U8'),
 array([['Berlin', 'Vienna', 'Paris', 'Budapest']], dtype='<U8')]