In [3]:
import numpy as np

In [4]:
# One dimensional array
array_one = np.array([1,2,3,4])
array_one

array([1, 2, 3, 4])

In [5]:
# Array of zeros, initialize array quickly
array_of_zeros = np.zeros([3,4])
array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
# Array of ones, initialize array quickly
array_of_ones = np.ones([3,4])
array_of_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
# Specify data type
array_of_ones_dtype = np.ones([3,4], dtype=np.int16)
array_of_ones_dtype

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [26]:
# Empty array
array_empty = np.empty([3, 4])
array_empty

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
# Eye shape array, square with 1 in diagonal positions
array_eye = np.eye(3)
array_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
# Array in steps, last value is excluded
array_of_evens = np.arange(2,20,2)
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
# Array in steps, floats
array_of_floats = np.arange(0.2, 1.5, 0.3)
array_of_floats

array([0.2, 0.5, 0.8, 1.1, 1.4])

In [35]:
# Shape of array
array_of_evens.shape

(9,)

In [34]:
# Reshape 1d array
array_of_evens.reshape(3,3)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [32]:
# Reshape multidimensional array
array_43 = np.ones([4,3])
array_43

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
# Reshape multidimensional array
array_34 = array_43.reshape([3,4])
array_34

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
# New 1d array with same shape
array_new = np.ones_like(array_of_evens)
array_new

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [38]:
# New 1d array with same shape
array_new2 = np.zeros_like(array_of_evens)
array_new2

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [39]:
# New 2d array with same shape
array_new3 = np.zeros_like(array_34)
array_new3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [40]:
# Print array
print(array_of_evens)

[ 2  4  6  8 10 12 14 16 18]


In [41]:
# Print 2d array
print(array_34)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [42]:
# 3d array
array_3d = np.arange(24).reshape([2,3,4])
print(array_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [49]:
# Print large array
array_10000 = np.arange(10000)
print(array_10000)

[   0    1    2 ... 9997 9998 9999]


In [50]:
np.set_printoptions(threshold=np.nan)