In [1]:
import numpy as np

In [2]:
salaries = np.genfromtxt('../Data/numpy-working-with-multidimensional-data/02/demos/data/salary.csv', delimiter=',')

In [3]:
salaries

array([60000., 58000., 56967., ..., 54647., 25000., 70000.])

In [8]:
print('Mean = {}'.format(str(np.mean(salaries))))
print('Median = {}'.format(str(np.median(salaries))))
print('Std Deviation = {}'.format(str(np.std(salaries))))
print('Variance = {}'.format(str(np.var(salaries))))

Mean = 55894.53879686138
Median = 48000.0
Std Deviation = 55170.37550939316
Variance = 3043770333.8474483


In [9]:
a = np.arange(20)

In [10]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
# Step slicing
a[2:10:2]

array([2, 4, 6, 8])

In [16]:
# Traverse in reverse order
a[:10:-2]

array([19, 17, 15, 13, 11])

In [17]:
import pandas as pd

In [22]:
df = pd.Series([1, 2, 3, 4, 5, 6])
df[1:3:-1]

Series([], dtype: int64)

In [24]:
asq = np.arange(10)**2
asq

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [25]:
# iterate over 1d array
for i in asq:
    print(i*2)

0
2
8
18
32
50
72
98
128
162


In [32]:
# iterate over 2d array, row dimension
students = np.array([['john', 'adam', 'jane'], [1, 2, 3], [10, 20, 30]])
for i in students:
    print(i)

In [28]:
# iterate over 2d array, row wise, flatten returns result
for i in students.flatten():
    print(i)

john
adam
jane
1
2
3
10
20
30


In [31]:
# iterate over 2d array, column wise, flatten returns array/series
for i in students.flatten(order='F'):
    print(i)

john
1
10
adam
2
20
jane
3
30


In [40]:
# iterate over 2d array, row wise, nditer does not return array/series
for i in np.nditer(students):
    print(i)

john
adam
jane
1
2
3
10
20
30


In [41]:
# iterate over 2d array, column wise, nditer does not return array/series
for i in np.nditer(students, order='F'):
    print(i)

john
1
10
adam
2
20
jane
3
30


In [43]:
# iterate over 2d array, column wise, return vector, nditer does not return array/series
for i in np.nditer(students, order='F', flags = ['external_loop']):
    print(i)

['john' '1' '10']
['adam' '2' '20']
['jane' '3' '30']


In [47]:
# iterate over 2d array, column wise, return vector, assignable, nditer does not return array/series
for i in np.nditer(students, order='F', flags = ['external_loop'], op_flags =['readwrite']):
    i[...] = i

In [51]:
# nditer does not return array/series
a = np.nditer(students, order='F')
a

In [53]:
# flatten returns array/series
b = students.flatten(order='F')
b

array(['john', '1', '10', 'adam', '2', '20', 'jane', '3', '30'],
      dtype='<U4')