In [1]:
import numpy as np

In [2]:
a = np.array([['Germany', 'Austria', 'France', 'Hungary'], ['Berlin', 'Vienna', 'Paris', 'Budapest']])

In [3]:
a

array([['Germany', 'Austria', 'France', 'Hungary'],
       ['Berlin', 'Vienna', 'Paris', 'Budapest']], dtype='<U8')

In [4]:
a.shape

(2, 4)

In [7]:
# Copy is made only if needed, only if shape has changed
a.ravel()

array(['Germany', 'Austria', 'France', 'Hungary', 'Berlin', 'Vienna',
       'Paris', 'Budapest'], dtype='<U8')

In [8]:
# Transpose
a.T

array([['Germany', 'Berlin'],
       ['Austria', 'Vienna'],
       ['France', 'Paris'],
       ['Hungary', 'Budapest']], dtype='<U8')

In [9]:
a.reshape(4,2)

array([['Germany', 'Austria'],
       ['France', 'Hungary'],
       ['Berlin', 'Vienna'],
       ['Paris', 'Budapest']], dtype='<U8')

In [10]:
a

array([['Germany', 'Austria', 'France', 'Hungary'],
       ['Berlin', 'Vienna', 'Paris', 'Budapest']], dtype='<U8')

In [14]:
b = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
b.shape

(3, 4)

In [17]:
b.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [21]:
b[1]

array([5, 6, 7, 8])

In [22]:
b.reshape(-1,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])