In [2]:
import numpy as np
import pandas as pd

In [2]:
x = np.array([3,2,2])
B = np.array([[1,0],[0,1],[0,1]])

In [8]:
pi_u_x = B @ np.linalg.inv(B.T @ B) @ B.T @ x

In [9]:
pi_u_x

array([3., 2., 2.])

In [10]:
x = np.array([12,0,0])
B = np.array([[1,0],[1,1],[1,2]])

In [11]:
pi_u_x = B @ np.linalg.inv(B.T @ B) @ B.T @ x

In [12]:
pi_u_x

array([10.,  4., -2.])

In [3]:
b = np.array([1,2,2])

In [4]:
norm_b = np.linalg.norm(b)
norm_b

3.0

In [6]:
pm_1d = ( b * b.T ) / (np.linalg.norm(b) ** 2)
pm_1d

array([0.11111111, 0.44444444, 0.44444444])