In [27]:
import csv
import pandas as pd
import numpy as np

## Misc commands

In [28]:
# set floating point precision
%precision 2

'%.2f'

In [29]:
# make series from dictionary
a = {'golf': 'usa', 'football': 'brazil', 'cricket': 'india', 'chess': 'russia'}
a_series = pd.Series(a)
a_series

golf           usa
football    brazil
cricket      india
chess       russia
dtype: object

In [30]:
%%timeit -n5 # python magic functions
a_series.iloc[0]

5.99 µs ± 3.05 µs per loop (mean ± std. dev. of 7 runs, 5 loops each)


## Random numbers

In [31]:
# Create an array of the given shape and populate it with random samples from a uniform distribution 
# over [0, 1).
# parameter is dimensions of array (optional). If not supplied, will return single value
# https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html
np.random.rand(10)

array([0.96, 0.23, 0.63, 0.7 , 0.27, 0.21, 0.6 , 0.43, 0.81, 0.16])

In [32]:
# https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html
np.random.rand()

0.22

In [33]:
# https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html
np.random.randint(100)

30

In [34]:
np.random.randint(0, 10)

4

In [35]:
np.random.randint(0, 10, (3, 4))

array([[5, 1, 7, 1],
       [7, 7, 0, 6],
       [3, 1, 5, 8]])

In [36]:
type(np.random.randint(0, 10, (3, 4))[0,0])

numpy.int32

In [37]:
np.random.randint(0, 10, (3, 4), dtype=np.uint8)

array([[7, 7, 3, 5],
       [7, 7, 8, 7],
       [5, 5, 6, 7]], dtype=uint8)

In [38]:
type(np.random.randint(0, 10, (3, 4), dtype=np.uint8)[0,0])

numpy.uint8

In [39]:
np.random.normal(size=10)

array([-1.05, -1.4 , -1.58, -0.42,  0.46, -0.3 ,  1.12, -0.86, -0.03,
       -1.06])