In [1]:
import numpy as np

In [4]:
X_test = np.arange(6).reshape(2,3)

In [5]:
print(X_test)

[[0 1 2]
 [3 4 5]]


In [6]:
D, N = X_test.shape
mean = np.zeros((D,1))
### Edit the code; iterate over the dataset and compute the mean vector.
for n in range(N):
    # Update the mean vector
    print(n)
    


0
1
2


In [20]:
mean = np.zeros((D,1))
mean[:,0] = X_test[:,0]
print(mean)
mean[:,0] = ((mean[:,1-1] * 1) + X_test[:,1])/(1+1)
mean[:,0] = ((mean[:,0] * 2) + X_test[:,2])/(2+1)
print(mean)

[[0.]
 [3.]]
[[1.]
 [4.]]


In [33]:
mean = np.zeros((D,1))
mean[0,0] = 2#np.mean(X_test[0,:])
mean[1,0] = np.mean(X_test[1,:])
print(mean)
# np.mean(X_test[0,:])

[[2.]
 [4.]]


In [ ]:
D, N = X.shape
    

In [13]:
np.sum(X_test[1])

12

In [15]:
def mean_naive(X):
    "Compute the mean for a dataset X nby iterating over the data points"
    # X is of size (D,N) where D is the dimensionality and N the number of data points
    D, N = X.shape
    mean = np.zeros((D,1))
    ### Edit the code; iterate over the dataset and compute the mean vector.
    for n in range(N):
        # Update the mean vector
        mean = ((mean * (n-1)) + X[n])/n
    ###
    return mean

In [17]:
X_test[0]

array([0, 1, 2])

In [22]:

# mean = np.zeros((D,1))
### Edit the code; iterate over the dataset and compute the mean vector.
for n in range(N):
    # Update the mean vector
#     mean = ((mean * (n-1)) + X[n])/n
    print(n)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [18]:
A = np.array([[90,60,90],[90,90,30],[60,60,60],[60,60,90],[30,30,30]])
A

array([[90, 60, 90],
       [90, 90, 30],
       [60, 60, 60],
       [60, 60, 90],
       [30, 30, 30]])

In [19]:
A_cov = np.cov(A)
A_cov

array([[ 300., -300.,    0.,  150.,    0.],
       [-300., 1200.,    0., -600.,    0.],
       [   0.,    0.,    0.,    0.,    0.],
       [ 150., -600.,    0.,  300.,    0.],
       [   0.,    0.,    0.,    0.,    0.]])

In [21]:
X_test = np.arange(6).reshape(2,3)
X_test_cov = np.cov(X_test)
X_test_cov

array([[1., 1.],
       [1., 1.]])

In [14]:
A_1 = np.array([[24,24,-6,-6,-36],[0,30,0,0,-30],[30,-30,0,30,-30]])
A_1

array([[ 24,  24,  -6,  -6, -36],
       [  0,  30,   0,   0, -30],
       [ 30, -30,   0,  30, -30]])

In [15]:
A_2 = (A_1)@(A_1.T)
A_2

array([[2520, 1800,  900],
       [1800, 1800,    0],
       [ 900,    0, 3600]])

In [16]:
A_3 = A_2/5
A_3

array([[504., 360., 180.],
       [360., 360.,   0.],
       [180.,   0., 720.]])

In [23]:
B = np.array([[0,1,2],[3,4,5]])
B

array([[0, 1, 2],
       [3, 4, 5]])

In [24]:
B_mean = [2,2.5,3.5]

In [25]:
B_1 = np.array([[-1,-1.5,-1.5],[1,1.5,1.5]])
B_1

array([[-1. , -1.5, -1.5],
       [ 1. ,  1.5,  1.5]])

In [26]:
B_2 = (B_1)@(B_1.T)
B_2

array([[ 5.5, -5.5],
       [-5.5,  5.5]])

In [29]:
B_3 = B_2/2
B_3

array([[ 2.75, -2.75],
       [-2.75,  2.75]])